package com.inner_classes.Member_inner_class;

//Java Member inner class
/*Üst:kapsayan alt:kapsanan
 * Alt sýnýf üst sýnýfýn deðiþken ve metodlara ulaþabilir
 * Alt sýnýfdan nesne üretmek için üst sýnýfdan nesne üretmek þarttýr
 * Derlendiði zaman:
 * App.class
 * App$Inner.class
classlarý oluþur*/

public class App {

	private int data = 30;

	class Inner {

		void msg() {

			System.out.println("data is " + data);
		}
	}

	public static void main(String args[]) {

		App obj = new App();
		App.Inner in = obj.new Inner();
		in.msg();
	}
}

// Internal code generated by the compiler
/*
class App$Inner {

	final App this$0;

	App$Inner() {

		super();
		this$0 = App.this;
	}

	void msg() {

		System.out.println((new StringBuilder()).append("data is ").append(App.access$000(App.this)).toString());
	}
}
*/